# Generated by Django 4.2.27 on 2026-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
